ports:
  - ${NGINX_HTTP_EXPORT_PORT}:80
  - ${NGINX_HTTPS_EXPORT_PORT}:443
volumes:
  - "${NGINX_DIR}/nginx.conf:/etc/nginx/nginx.conf"
  - "${NGINX_DIR}/html:/usr/share/nginx/html"
  - "${NGINX_DIR}/conf.d:/etc/nginx/conf.d"
  - "${NGINX_DIR}/ssl:/etc/nginx/ssl"
  - "${NGINX_DIR}/logs:/var/log/nginx"
