ports:
  - "${RABBITMQ_EXPORT_PORT}:5672"
  - "${RABBITMQ_EXPORT_WEB_PORT}:15672"
volumes:
  - ${RABBITMQ_DIR}/data/:/var/lib/rabbitmq/
  - ${RABBITMQ_DIR}/log/:/var/log/rabbitmq/
environment:
  RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
  RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
