image: ${MYSQL_SERVER_IMAGE}
ports:
  - "${MYSQL_SERVER_EXPORT_PORT}:3306"
volumes:
  - "${MYSQL_SERVER_DIR}/data:/var/lib/mysql"
  - "${MYSQL_SERVER_DIR}/config/my.cnf:/etc/my.cnf"
  - "${MYSQL_SERVER_DIR}/config/my.cnf.d:/etc/my.cnf.d"
-name: "mysql"
