image: ${GRAFANA_IMAGE}
user: root
ports:
  - "${GRAFANA_EXPORT_PORT}:3000"
volumes:
  - "${GRAFANA_DIR}/etc:/etc/grafana/"
  - "${GRAFANA_DIR}/data:/var/lib/grafana/"
  - "${GRAFANA_DIR}/log:/var/log/grafana/"
